mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  typeAliasesPackage: ltd.ygao.oneblog.pojo
server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
    max-http-form-post-size: -1
spring:
  datasource:
    password: 123456
    url: jdbc:mysql:///oneblog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
configuration:
  map-underscore-to-camel-case: true
  cache-enabled: false
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mconfig:
  swagger-ui-open: true
jedis :
  pool :
    host : 192.168.0.102
    port : 6379
    ##password: Yl09281011
    timeout: 10000
    config :
      maxTotal: 100
      maxIdle: 10
      maxWaitMillis : 100000